automecom/urls.py
from django.urls import path
from . import views

app_name = "automecom"
urlpatterns = [
    path('', views.home_view, name="Dashboard"),
    path('home.html', views.home_view, name="Home"),
    path('servico.html', views.servico_view, name="Servico"),
    path('create.html', views.servico_create, name="Create"),
    path('edit/<int:post_id>', views.servico_edit, name='editar'),
    path('delete/<int:post_id>', views.servico_delete, name='apagar'),
    path('conselhos.html', views.conselho_view, name="Conselho"),
    path('contactos.html', views.contacto_view, name="Contacto"),
    path('sobre.html', views.sobre_view, name="Sobre"),
    path('marcacao', views.marcacao_view, name="Marcação"),
    path('login.html', views.view_login, name='login'),
    path('logout', views.view_logout, name='logout'),
    path('register.html', views.register_view, name='register'),
    path('perfil.html', views.perfil_view, name="perfil"),
    path('marcacoes', views.marcacoes_view, name="marcacoes"),
    path('editmarc/<int:post_id>', views.marcacao_edit, name='editarmarc'),
    path('deletemarc/<int:post_id>', views.marcacao_delete, name='apagarmarc'),
    path('garantia.html', views.garantia_view, name='garantia'),
    path('privacidade.html', views.privacidade_view, name='privacidade'),
    path('obras.html', views.obras_view, name='obras'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('automecom.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

automecom/models.py
from django.contrib.auth.models import User
from django.db import models


class TipoServico(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Servico(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=350, default="", blank=True)
    tipo = models.ManyToManyField(TipoServico)

    def __str__(self):
        return self.nome


class Veiculo(models.Model):
    marca = models.CharField(max_length=200)
    modelo = models.CharField(max_length=200)
    ano = models.PositiveIntegerField(default=0000)
    matricula = models.CharField(max_length=8)
    kms = models.IntegerField(default=0)

    def __str__(self):
        return self.marca + " " + self.modelo


class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    administrador = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Marcacao(models.Model):
    utilizador = models.ForeignKey(Utilizador, on_delete=models.CASCADE, related_name="marcacoes", blank=True,
                                   null=True)
    nome = models.CharField(max_length=200)
    apelido = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    telefone = models.IntegerField()
    servicos = models.ManyToManyField(Servico)
    veiculo = models.OneToOneField(Veiculo, on_delete=models.CASCADE)
    data = models.CharField(max_length=200, default=0)
    hora = models.CharField(max_length=200, default=0)
    descricao = models.TextField(max_length=500)

    ESTADOS = [
        ('Por confirmar', 'Por confirmar'),
        ('Confirmado', "Confirmado"),
        ('Terminado', 'Terminado')
    ]
    estado = models.CharField(max_length=50, choices=ESTADOS, default='Por confirmar')

    numero = models.IntegerField(default=0)
    orcamento = models.FileField(upload_to='tarefas/', null=True, blank=True)
    observacoes = models.TextField(max_length=500, default=" ")
    fatura = models.FileField(upload_to='tarefas/', null=True, blank=True)

    def __str__(self):
        return f"{self.nome} - {self.data}"

automecom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User

from .models import Servico, Utilizador, Veiculo, Marcacao, TipoServico
from .widget import DatePickerInput, TimePickerInput


class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ['tipo', 'nome', 'descricao']


class TipoServicoForm(forms.ModelForm):
    class Meta:
        model = TipoServico
        fields = ['nome']


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Nome próprio'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Apelido'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['placeholder'] = 'Palavra passe'
        self.fields['password2'].widget.attrs['placeholder'] = '********'

        self.fields['username'].help_text = '150 caracteres ou menos. Somente letras, dígitos e @/./+/-/_.'
        self.fields['password1'].help_text = 'Sua senha deve conter pelo menos 8 caracteres.'
        self.fields['password2'].help_text = 'Digite a mesma senha de antes, para verificação.'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = '150 caracteres ou menos. Somente letras, dígitos e @/./+/-/_.'


class UtilizadorForm(forms.ModelForm):
    class Meta:
        model = Utilizador
        fields = []


class PasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['placeholder'] = 'Senha atual'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'Nova senha'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirme a nova senha'

        self.fields['new_password1'].help_text = ''


class VeiculoForm(forms.ModelForm):
    class Meta:
        model = Veiculo
        fields = ['marca', 'modelo', 'ano', 'matricula', 'kms']


class MarcacaoForm(forms.Form):
    nome = forms.CharField(max_length=200)
    apelido = forms.CharField(max_length=200)
    email = forms.CharField(max_length=200)
    servicos = forms.ModelMultipleChoiceField(queryset=Servico.objects.all())
    telefone = forms.IntegerField()
    descricao = forms.CharField(max_length=500)
    data = forms.DateField(widget=DatePickerInput)
    hora = forms.TimeField(widget=TimePickerInput)


class MarcacaoEditForm(forms.ModelForm):
    class Meta:
        model = Marcacao
        fields = ['nome', 'apelido', 'email', 'servicos', 'telefone', 'data', 'descricao', 'estado', 'hora',
                  'orcamento', 'observacoes', 'fatura']


class MarcacaoEditFormClient(forms.ModelForm):
    class Meta:
        model = Marcacao
        fields = ['nome', 'apelido', 'email', 'servicos', 'telefone', 'data', 'descricao', 'hora']

automecom/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from automecom.templatetags.custom_tags import is_administrador
from .forms import ServicoForm, UtilizadorForm, UserForm, PasswordForm, RegisterForm, MarcacaoForm, VeiculoForm, \
    MarcacaoEditForm, MarcacaoEditFormClient
from .models import Servico, Utilizador, Veiculo, Marcacao
from django import template

register = template.Library()


def is_superuser(user):
    return user.is_superuser


def home_view(request):
    return render(request, 'automecom/home.html')


@login_required
def view_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('automecom:Home'))


def view_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username=username,
            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('automecom:Home'))
        else:
            return render(request, 'automecom/login.html', {
                'message': 'Credenciais invalidas.'
            })

    return render(request, 'automecom/login.html')


def servico_view(request):
    servicos = Servico.objects.all()

    return render(request, 'automecom/servico.html',
                  {'servicos': servicos, 'administrador': is_administrador(request.user)})


def servico_create(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('automecom:login'))

    if not is_administrador(request.user):
        return HttpResponseRedirect(reverse('automecom:Home'))

    if request.method == 'POST':
        form = ServicoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('automecom:Servico'))
    form = ServicoForm()

    context = {'form': form}
    return render(request, 'automecom/create.html', context)


def servico_edit(request, post_id):
    if not is_administrador(request.user):
        return HttpResponseRedirect(reverse('automecom:Home'))

    post = Servico.objects.get(id=post_id)
    if request.method == 'POST':
        form = ServicoForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('automecom:Servico'))
    else:
        form = ServicoForm(instance=post)
    context = {'form': form, 'post_id': post_id}
    return render(request, 'automecom/edit.html', context)


@login_required
def servico_delete(request, post_id):
    if Servico.objects.filter(pk=post_id).exists():
        Servico.objects.get(pk=post_id).delete()
    return HttpResponseRedirect(reverse('automecom:Servico'))


def conselho_view(request):
    return render(request, 'automecom/conselhos.html')


def contacto_view(request):
    return render(request, 'automecom/contactos.html')


def garantia_view(request):
    return render(request, 'automecom/garantia.html')


def privacidade_view(request):
    return render(request, 'automecom/privacidade.html')


def obras_view(request):
    utilizador = Utilizador.objects.get(user=request.user)
    context = {
        "marcacoes": Marcacao.objects.filter(utilizador_id=utilizador),
        "estado": Marcacao.estado,
        "data": Marcacao.data,
        "hora": Marcacao.hora,
    }
    if is_administrador(request.user):
        context = {
            "marcacoes": Marcacao.objects.all(),
            "estado": Marcacao.estado,
            "data": Marcacao.data,
            "hora": Marcacao.hora,
        }
    return render(request, 'automecom/obras.html', context)


def sobre_view(request):
    return render(request, 'automecom/sobre.html')


def marcacoes_view(request):
    utilizador = Utilizador.objects.get(user=request.user)
    context = {
        "marcacoes": Marcacao.objects.filter(utilizador_id=utilizador),
        "estado": Marcacao.estado,
        "descricao": Marcacao.descricao,
        "data": Marcacao.data,
        "hora": Marcacao.hora,
    }
    if is_administrador(request.user):
        context = {
            "marcacoes": Marcacao.objects.all(),
            "estado": Marcacao.estado,
            "descricao": Marcacao.descricao,
            "data": Marcacao.data,
            "hora": Marcacao.hora,
            "fatura": Marcacao.fatura,
        }
    return render(request, 'automecom/marcacoes.html', context)


def register_view(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'automecom/register.html', {'form': form})

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username
            utilizador = Utilizador()
            utilizador.nome = user.username
            utilizador.user = user
            user.save()
            utilizador.save()
            login(request, user)
            return redirect('automecom:Home')
        else:
            return render(request, 'automecom/register.html', {'form': form})


def perfil_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('automecom:login'))

    post = Utilizador.objects.get(user=request.user)
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=request.user)
        form2 = UtilizadorForm(request.POST, request.FILES, instance=post)
        form3 = PasswordForm(request.user, request.POST)
        if form.is_valid():
            if form2.is_valid():
                if form3.is_valid():
                    form.save()
                    form2.save()
                    form3.save()
            return HttpResponseRedirect(reverse('automecom:perfil'))
    else:
        form = UserForm(instance=request.user)
        form2 = UtilizadorForm(instance=post)
        form3 = PasswordForm(request.user)
        context = {'form': form, 'form2': form2, 'form3': form3}
    return render(request, 'automecom/perfil.html', context)


@login_required
def utilizador_delete(request, post_id):
    if Utilizador.objects.filter(pk=post_id).exists():
        logout(request)
        Utilizador.objects.get(pk=post_id).user.delete()
    return HttpResponseRedirect(reverse('automecom:Home'))


def marcacao_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('automecom:login'))
    if request.method == 'GET':
        form = MarcacaoForm()
        form2 = VeiculoForm()
        if request.user.is_authenticated:
            del form.fields['nome']
            del form.fields['apelido']
            del form.fields['email']
        return render(request, 'automecom/marcacao.html', {'form': form, 'form2': form2})

    if request.method == 'POST':
        form = MarcacaoForm()
        form2 = VeiculoForm(request.POST)
        if form2.is_valid():
            if request.user.is_authenticated:

                veiculo = form2.save()
                marcacao = Marcacao(nome=request.user.first_name, apelido=request.user.last_name,
                                    email=request.user.email, telefone=request.POST['telefone'], veiculo=veiculo,
                                    data=request.POST['data'], hora=request.POST['hora'],
                                    descricao=request.POST['descricao'])
                utilizador = Utilizador.objects.get(user=request.user)
                marcacao.utilizador = utilizador
                marcacao.save()
            else:
                veiculo = form2.save()
                marcacao = Marcacao(nome=request.POST['nome'], apelido=request.POST['apelido'],
                                    email=request.POST['email'], telefone=request.POST['telefone'], veiculo=veiculo,
                                    data=request.POST['data'], hora=request.POST['hora'],
                                    descricao=request.POST['descricao'])
                marcacao.save()
            return redirect('automecom:marcacoes')
        else:
            return render(request, 'automecom/marcacao.html', {'form': form, 'form2': form2})


def marcacao_edit(request, post_id):
    post = Marcacao.objects.get(id=post_id)
    if not is_administrador(request.user) and post.utilizador.user != request.user:
        return HttpResponseRedirect(reverse('automecom:Home'))

    if request.method == 'POST':
        if is_administrador(request.user):
            form = MarcacaoEditForm(request.POST or None, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('automecom:marcacoes'))
        else:
            form = MarcacaoEditFormClient(request.POST or None, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('automecom:marcacoes'))
    else:
        if is_administrador(request.user):
            form = MarcacaoEditForm(instance=post)
        else:
            form = MarcacaoEditFormClient(instance=post)
        context = {'form': form, 'post_id': post_id}
        return render(request, 'automecom/editmarcacao.html', context)


def marcacao_delete(request, post_id):
    if Marcacao.objects.filter(pk=post_id).exists():
        Marcacao.objects.get(pk=post_id).delete()
    return HttpResponseRedirect(reverse('automecom:marcacoes'))

automecom/templates/automecom/contactos.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Contactos</title>
</head>
{% extends 'automecom/layout.html' %}

{% block main %}
{% load static %}
<div class="contactos">
    <div class="containerrr">
        <div class="texttt">
            <h1>Auto Mecom</h1>
<br>
            <div>
            <h3>Oficina horário</h3>
                <br>
            <ul class="horario">
                <li>Seg  09:00 a 18:00</li>
                <li>Ter  09:00 a 18:00</li>
                <li>Qua  09:00 a 18:00</li>
                <li>Qui  09:00 a 18:00</li>
                <li>Sex  09:00 a 18:00</li>
                <li>Sab  Encerrado</li>
                <li>Dom  Encerrado</li>
            </ul>
        </div>
        <div>
            <br>
            <br>
            <p>
            Estr. Manuel Correia Lopes 576<br>
            2785-543 São Domingos de Rana
            </p>
        </div>
        <div class="contact-info">
            <p>Tel. 21 445 1746</p>
        </div>
        <div class="contact-info">
            <p>E-mail. geral@automecom.com</p>
        </div>
        </div>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12449.948005096685!2d-9.3224715!3d38.7295854!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd1ecee2af2d6dd1%3A0xbca453df95bf3380!2sAuto%20Mecom%20Unipessoal%2C%20Lda!5e0!3m2!1spt-PT!2spt!4v1697317659783!5m2!1spt-PT!2spt" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>
{% endblock %}

automecom/templates/automecom/create.html
{% extends 'automecom/layout.html' %}


{% block main %}
<section>
<h3>Novo Serviço</h3>
<form method ="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="gravar">
        <input type="submit" value="Gravar">
    </div>
</form>
</section>
{% endblock %}

automecom/templates/automecom/edit.html
{% extends 'automecom/layout.html' %}


{% block main %}
<h3>Novo Post</h3>
<section>
<form method ="POST" action="{% url 'automecom:editar'  post_id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'automecom:Servico' %}" role="button">Cancelar</a>
    <div class="gravar">
        <input type="submit" value="Gravar">
    </div>
    <a href="{% url 'automecom:apagar' post_id %}" role="button">Apagar</a>
</form>
</section>
{% endblock %}

automecom/templates/automecom/editmarcacao.html
{% extends 'automecom/layout.html' %}


{% block main %}
<section>
<form method ="POST" action="{% url 'automecom:editarmarc'  post_id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'automecom:Marcação' %}" role="button">Cancelar</a>
    <div class="gravar">
        <input type="submit" value="Gravar">
    </div>
    <a href="{% url 'automecom:apagarmarc' post_id %}" role="button">Apagar</a>
</form>
</section>
{% endblock %}

automecom/templates/automecom/home.html
{% extends 'automecom/layout.html' %}

{% block main %}
{% load static %}
<div class="slideshow-container">
  <div class="mySlides fade">
    <img class="imagem" src="{% static 'automecom/images/foraauto.jpg' %}" alt="imagem1">
  </div>

  <div class="mySlides fade">
    <img class="imagem" src="{% static 'automecom/images/equipaauto.jpg' %}" alt="imagem2">
  </div>

  <div class="mySlides fade">
    <img class="imagem" src="{% static 'automecom/images/autodentro.JPG' %}" alt="imagem3">
  </div>

  <div class="mySlides fade">
    <img class="imagem" src="{% static 'automecom/images/pintura.jpg' %}" alt="imagem3">
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

    <script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>
    <div class="promo">
        <div>
            <a href=""><img class="promoimg" src="{% static 'automecom/images/promolampada.png' %}" alt="imagem4"></a>
        </div>
        <div>
            <img class="promoimg" src="{% static 'automecom/images/promo2.jpg' %}" alt="imagem4">
        </div>
    </div>
    <div class="comprido">
            <img class="promoimg" src="{% static 'automecom/images/promooo.png' %}" alt="imagem5" width="40%">
    </div>

{% endblock %}

automecom/templates/automecom/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Login</title>
</head>

{% extends "automecom/layout.html" %}

{% block main %}
{% load static %}
<div class="subblock">
<div class="loginblock">
    <h1 class="textmenu">Ainda não tem conta</h1><br>
<div class="registar">
    <button class="loginb"><a href="register.html">Registar</a></button>
</div>
<br>
<br>
    <h1 class="textmenu">Já tem conta?</h1>
    <br>
<br>
    {% if message %}
      <p> {{ message }} </p>
    {% endif %}

    <form action="{% url 'automecom:login' %}" method="post">
        {% csrf_token %}
        <label>
            <input type="text" name="username" placeholder="username">
        </label><br><br>
        <label>
            <input type="password" name="password" placeholder="password">
        </label>
        <br>
        <br>
        <br>

        <input class="submit" type="submit" value="Login">
    </form>
</div>
</div>
{% endblock main %}

automecom/templates/automecom/marcacao.html
{% extends 'automecom/layout.html' %}
{% load custom_tags %}

    {% block styles %}
        <style>
        th {
            text-align:right;
        }
        td {
            width: 100%;
        }
        </style>

    {% endblock %}

{% block main %}
{% load static %}
<div class="containermarc">
<div class="marcacoes-container">
    <form action="{% url 'automecom:Marcação' %}" method="post">
        {% csrf_token %}
        <div class="marcacao">
            <h2>Marcação</h2><br>
            <table>
                {{ form }}
            </table>
        </div>

        <div class="marcacao">
            <br>
            <h2>Veículo</h2>
            <br>
            <table>
                {{ form2 }}
            </table>
        </div>
        <bR>

        <button class="buttonmarc" type="submit">Marcar</button>
    </form>
</div>
</div>
{% endblock %}

automecom/templates/automecom/obras.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Obras </title>
</head>

{% extends 'automecom/layout.html' %}
{% load custom_tags %}

{% block main %}
{% load static %}

<body>
<section>
{% for marcacao in marcacoes %}
    {% if marcacao.estado == "Terminado" %}
    <div class="Serv">
        <div>
            <br>
            {% if user|is_administrador %}
            <p>Cliente: {{marcacao.nome}} {{marcacao.apelido}}</p>
            <p>Veículo: {{marcacao.veiculo}}</p>
            {% for servico in marcacao.servicos.all %}
            <p>Serviço(s): {{ servico.nome }}</p>
            {% endfor %}
            <p>Data: {{marcacao.data}} / {{marcacao.hora}}</p>
            <p>Observações: {{ marcacao.observacoes }}</p>
            <p>Estado: {{marcacao.estado}}</p>
                {% if marcacao.fatura %}
                    <p>Fatura: <a href="{{ marcacao.fatura.url }}" target="_blank">Ver Fatura</a></p>
                {% else %}
                    <p>Nenhuma fatura associada a esta obra.</p>
                {% endif %}
            {% else %}
            <p>Data da obra : {{marcacao.data}}</p>
            <p>Veículo : {{marcacao.veiculo}}</p>
            {% for servico in marcacao.servicos.all %}
            <p>Serviço(s): {{ servico.nome }}</p>
            {% endfor %}
            <p>Observações : {{ marcacao.observacoes }}</p>
                {% if marcacao.fatura %}
                    <p>Fatura: <a href="{{ marcacao.fatura.url }}" target="_blank">Ver Fatura</a></p>
                {% else %}
                    <p>Nenhuma fatura associada a esta marcação.</p>
                {% endif %}
            {% endif %}
            <br>
        </div>
    </div>
    {% if user|is_administrador %}
    <a href="{% url 'automecom:editarmarc' marcacao.id %}" class="botao">Editar</a>
    <a href="{% url 'automecom:apagarmarc' marcacao.id %}" class="botao">Apagar</a>
    {% endif %}
    <br>
    {% endif %}
{% endfor %}
</section>

</body>
</html>
{% endblock %}

automecom/templates/automecom/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Perfil</title>
</head>
{% extends 'automecom/layout.html' %}

{% block main %}
{% load static %}
<body>
<section>
<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form2.as_p }}
    {{ form3.as_p }}
    <a href="{% url 'automecom:Home' %}" role="button">Cancelar</a>
    <div class="gravar">
        <input type="submit" value="Gravar">
    </div>
</form>
</section>
</body>
</html>
{% endblock %}

automecom/templates/automecom/register.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Registar</title>
</head>
{% extends 'automecom/layout.html' %}

{% block main %}
{% load static %}
<div class="subblock2">
<div class="loginblock2">

{% block content %}

<form method="POST" novalidate>
	{% csrf_token %}
	<h2>Criação de conta</h2><br><br>
	{{ form.as_p }}
    <br>
	<input class="submit" type="submit" value="Criar a minha conta" />
</form>
</div>
</div>
{% endblock content%}
{% endblock %}

automecom/templates/automecom/servico.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auto Mecom | Serviços</title>
</head>

{% extends 'automecom/layout.html' %}
{% load custom_tags %}

{% block main %}
{% load static %}
<body>

<div class="cabeçalho"></div><br>

<div class="Serviços">

<p class="SMALL">Na oficina mecânica Auto Mecom, a nossa equipa presta serviços especializados em manutenção e reparação auto, todos os dias.</p>

<p class="BIG">Seja qual for o problema do seu veículo, pode sempre contar com a nossa experiência e profissionalismo para o resolvermos.</p>
<br><br>
<section>
{% for Servico in servicos %}
    <div class="Serv">
        <div>
        <h3>{{Servico.nome}}</h3>
        <p class="SMALL">{{Servico.descricao}}</p>
        </div>
    </div>
     {% if user|is_administrador %}
    <a href="{% url 'automecom:editar' Servico.id %}" class="botao">Editar</a>
    <a href="{% url 'automecom:apagar' Servico.id %}" class="botao">Apagar</a>
    {% endif %}
    <br>
    <br>
{% endfor %}
</section>
    {% if administrador %}
        <p style="text-align: center"><a href="{% url 'automecom:Create' %}" class="botao">+ Adicionar Serviço</a></p>
    {% endif %}
    </div>
</body>
</html>
    <br>
    <br>
    <br>
    <br>
{% endblock %}